In [4]:
from pandas import read_csv

In [5]:
dataframe = read_csv("../data/raw/houses_madrid.csv")
dataframe.head()

,Unnamed: 0,id,title,subtitle,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,...,energy_certificate,has_parking,has_private_parking,has_public_parking,is_parking_included_in_price,parking_price,is_orientation_north,is_orientation_west,is_orientation_south,is_orientation_east
0,0,21742,"Piso en venta en calle de Godella, 64","San Cristóbal, Madrid",64.0,60.0,2,1.0,NaN,NaN,...,D,False,NaN,NaN,NaN,NaN,False,True,False,False
1,1,21741,Piso en venta en calle de la del Manojo de Rosas,"Los Ángeles, Madrid",70.0,NaN,3,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,21740,"Piso en venta en calle del Talco, 68","San Andrés, Madrid",94.0,54.0,2,2.0,NaN,NaN,...,no indicado,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,21739,Piso en venta en calle Pedro Jiménez,"San Andrés, Madrid",64.0,NaN,2,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,False,False,True,False
4,4,21738,Piso en venta en carretera de Villaverde a Val...,"Los Rosales, Madrid",108.0,90.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,True,True,True,True

In [6]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21742 entries, 0 to 21741
Data columns (total 58 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    21742 non-null  int64
 1   id                            21742 non-null  int64
 2   title                         21742 non-null  object
 3   subtitle                      21742 non-null  object
 4   sq_mt_built                   21616 non-null  float64
 5   sq_mt_useful                  8228 non-null   float64
 6   n_rooms                       21742 non-null  int64
 7   n_bathrooms                   21726 non-null  float64
 8   n_floors                      1437 non-null   float64
 9   sq_mt_allotment               1432 non-null   float64
 10  latitude                      0 non-null      float64
 11  longitude                     0 non-null      float64
 12  raw_address                   16277 non-null  object
 13  is_exact_address_hidden       21742 non-null  bool
 14  street_name                   15837 non-null  object
 15  street_number                 6300 non-null   object
 16  portal                        0 non-null      float64
 17  floor                         19135 non-null  object
 18  is_floor_under                20572 non-null  object
 19  door                          0 non-null      float64
 20  neighborhood_id               21742 non-null  object
 21  operation                     21742 non-null  object
 22  rent_price                    21742 non-null  int64
 23  rent_price_by_area            0 non-null      float64
 24  is_rent_price_known           21742 non-null  bool
 25  buy_price                     21742 non-null  int64
 26  buy_price_by_area             21742 non-null  int64
 27  is_buy_price_known            21742 non-null  bool
 28  house_type_id                 21351 non-null  object
 29  is_renewal_needed             21742 non-null  bool
 30  is_new_development            20750 non-null  object
 31  built_year                    10000 non-null  float64
 32  has_central_heating           13608 non-null  object
 33  has_individual_heating        13608 non-null  object
 34  are_pets_allowed              0 non-null      float64
 35  has_ac                        11211 non-null  object
 36  has_fitted_wardrobes          13399 non-null  object
 37  has_lift                      19356 non-null  object
 38  is_exterior                   18699 non-null  object
 39  has_garden                    1556 non-null   object
 40  has_pool                      5171 non-null   object
 41  has_terrace                   9548 non-null   object
 42  has_balcony                   3321 non-null   object
 43  has_storage_room              7698 non-null   object
 44  is_furnished                  0 non-null      float64
 45  is_kitchen_equipped           0 non-null      float64
 46  is_accessible                 4074 non-null   object
 47  has_green_zones               4057 non-null   object
 48  energy_certificate            21742 non-null  object
 49  has_parking                   21742 non-null  bool
 50  has_private_parking           0 non-null      float64
 51  has_public_parking            0 non-null      float64
 52  is_parking_included_in_price  7719 non-null   object
 53  parking_price                 7719 non-null   float64
 54  is_orientation_north          11358 non-null  object
 55  is_orientation_west           11358 non-null  object
 56  is_orientation_south          11358 non-null  object
 57  is_orientation_east           11358 non-null  object
dtypes: bool(5), float64(17), int64(6), object(30)
memory usage: 8.9+ MB

# Dataframe cleaning process 
To handle this dataframe, these are the following steps we are going to do : 
- Handle the Nulls values (drop observations, drop columns, replace with median / mean / value, etc...)
- Remove columns useless to regression model 
- Create sub column by analysing correlation
Let's clean this dataframe in [Cleaning notebook](../preprocess/cleaning.ipynb)